/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package multipleChoiceQuiz;

/**
 *
 * @author pehor9164
 */
public class MultipleChoiceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form MultipleChoiceQuiz
     */
    public MultipleChoiceQuiz() {
        initComponents();
        
        //Setting questions to invisible
        questionNumLbl.setVisible(false);
        questionLbl.setVisible(false);
        answerALbl.setVisible(false);
        answerBLbl.setVisible(false);
        answerCLbl.setVisible(false);
        answerDLbl.setVisible(false);
        
        //Publicly Declared Variables
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        instructionsLbl = new javax.swing.JLabel();
        instructionTwoLbl = new javax.swing.JLabel();
        instructionThreeLbl = new javax.swing.JLabel();
        instructionOneLbl = new javax.swing.JLabel();
        instructionFourLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        questionNumLbl = new javax.swing.JLabel();
        answerALbl = new javax.swing.JLabel();
        answerCLbl = new javax.swing.JLabel();
        answerDLbl = new javax.swing.JLabel();
        answerBLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        titleLbl.setText("Peter's Multiple Choice Quiz");
        jPanel1.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        instructionsLbl.setText("Instructions: ");
        jPanel1.add(instructionsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        instructionTwoLbl.setText("2) Type The Letter Of The Correct Answer Into The Box");
        jPanel1.add(instructionTwoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        instructionThreeLbl.setText("3) Press Submit");
        jPanel1.add(instructionThreeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        instructionOneLbl.setText("1) Read Question");
        instructionOneLbl.setOpaque(true);
        jPanel1.add(instructionOneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        instructionFourLbl.setText("4) Press Next");
        jPanel1.add(instructionFourLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        questionNumLbl.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        questionNumLbl.setText("Question #1");
        jPanel1.add(questionNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, 20));

        answerALbl.setText("A)");
        jPanel1.add(answerALbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, 20));

        answerCLbl.setText("C)");
        jPanel1.add(answerCLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 20));

        answerDLbl.setText("D)");
        jPanel1.add(answerDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 320, 20));

        answerBLbl.setText("B)");
        jPanel1.add(answerBLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 20));

        questionLbl.setFont(new java.awt.Font("Ti73pc", 0, 14)); // NOI18N
        questionLbl.setText("How Many Bits Are In A Byte?");
        jPanel1.add(questionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        //Setting Instructions to not visible 
        instructionsLbl.setVisible(false);
        instructionOneLbl.setVisible(false);
        instructionTwoLbl.setVisible(false);
        instructionThreeLbl.setVisible(false);
        instructionFourLbl.setVisible(false);
        //Setting Questions To Visible 
        questionNumLbl.setVisible(true);
        questionLbl.setVisible(true);
        answerALbl.setVisible(true);
        answerBLbl.setVisible(true);
        answerCLbl.setVisible(true);
        answerDLbl.setVisible(true);
        
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerALbl;
    private javax.swing.JLabel answerBLbl;
    private javax.swing.JLabel answerCLbl;
    private javax.swing.JLabel answerDLbl;
    private javax.swing.JLabel instructionFourLbl;
    private javax.swing.JLabel instructionOneLbl;
    private javax.swing.JLabel instructionThreeLbl;
    private javax.swing.JLabel instructionTwoLbl;
    private javax.swing.JLabel instructionsLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JLabel questionNumLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
